abstract class AppConsts {
  static const String fontFamily = 'Roboto';
  static const String quranIcon = 'assets/svg_icons/quran_icon.svg';
  static const String hadethIcon = 'assets/svg_icons/hadeth_icon.svg';
  static const String sebhaIcon = 'assets/svg_icons/sebha_icon.svg';
  static const String radioIcon = 'assets/svg_icons/radio_icon.svg';
  static const String timeIcon = 'assets/svg_icons/time_icon.svg';
  static const String mainHeaderBg = 'assets/images/img_header.png';
  static const String quranTabBg = 'assets/images/quran_tab.png';
  static const String mostRecently = 'assets/images/most_recent_bg.png';
  static const String hadethTabBg = 'assets/images/hadeth_tab.png';
  static const String splashScreen = 'assets/images/splash_screen.png';
  static const String introBg1 = 'assets/images/intro_bg1.png';
  static const String introBg2 = 'assets/images/intro_bg2.png';
  static const String introBg3 = 'assets/images/intro_bg3.png';
  static const String introBg4 = 'assets/images/intro_bg4.png';
  static const String introBg5 = 'assets/images/intro_bg5.png';
  static const String bg1Card = 'assets/images/bg1_card.png';
  static const String play = 'assets/svg_icons/play.svg';
  static const String pause = 'assets/svg_icons/pause.svg';
  static const String volumeHigh = 'assets/svg_icons/volume_high.svg';
  static const String volumeLow = 'assets/svg_icons/volume_low.svg';
  static const String soundWave = 'assets/images/sound_wave.png';
  static const String sebhaTabBg = 'assets/images/sebha_bg_tab.png';
  static const String sebhaBody = 'assets/images/sebhaBody 1.png';
  static const String sebhaTest = 'assets/images/header_sebha.png';
  static const String hadethPgae_bg = 'assets/images/hadethPgae_bg.png';
  static const String suraDetailsBg = 'assets/images/suraDetailsBg.png';
}
